import {
  columns,
  Products,
} from "@/components/utils/DataTable/Columns/ProductsColumn";
import DisplayPanel from "@/components/dashboard/DisplayPanel/DisplayPanel";

async function getData(): Promise<Products[]> {
  return [
    {
      id: "id-1",
      name: "Product 1",
      price: 10,
      stock: 5,
      category: "Category 1",
      status: "PUBLISHED",
      sku: "SKU-1",
    },
    {
      id: "id-2",
      name: "Product 2",
      price: 20,
      stock: 10,
      category: "Category 2",
      status: "DRAFT",
      sku: "SKU-2",
    },
    {
      id: "id-3",
      name: "Product 3",
      price: 30,
      stock: 15,
      category: "Category 3",
      status: "PUBLISHED",
      sku: "SKU-3",
    },
    {
      id: "id-4",
      name: "Product 4",
      price: 40,
      stock: 20,
      category: "Category 4",
      status: "DRAFT",
      sku: "SKU-4",
    },
    {
      id: "id-5",
      name: "Product 5",
      price: 50,
      stock: 25,
      category: "Category 5",
      status: "PUBLISHED",
      sku: "SKU-5",
    },
    {
      id: "id-6",
      name: "Product 6",
      price: 60,
      stock: 30,
      category: "Category 6",
      status: "DRAFT",
      sku: "SKU-6",
    },
    {
      id: "id-7",
      name: "Product 7",
      price: 70,
      stock: 35,
      category: "Category 7",
      status: "PUBLISHED",
      sku: "SKU-7",
    },
    {
      id: "id-8",
      name: "Product 8",
      price: 80,
      stock: 40,
      category: "Category 8",
      status: "DRAFT",
      sku: "SKU-8",
    },
    {
      id: "id-9",
      name: "Product 9",
      price: 90,
      stock: 45,
      category: "Category 9",
      status: "PUBLISHED",
      sku: "SKU-9",
    },
    {
      id: "id-10",
      name: "Product 10",
      price: 100,
      stock: 50,
      category: "Category 10",
      status: "DRAFT",
      sku: "SKU-10",
    },
    {
      id: "id-11",
      name: "Product 11",
      price: 110,
      stock: 55,
      category: "Category 11",
      status: "PUBLISHED",
      sku: "SKU-11",
    },
    {
      id: "id-12",
      name: "Product 12",
      price: 120,
      stock: 60,
      category: "Category 12",
      status: "DRAFT",
      sku: "SKU-12",
    },
    {
      id: "id-13",
      name: "Product 13",
      price: 130,
      stock: 65,
      category: "Category 13",
      status: "PUBLISHED",
      sku: "SKU-13",
    },
    {
      id: "id-14",
      name: "Product 14",
      price: 140,
      stock: 70,
      category: "Category 14",
      status: "DRAFT",
      sku: "SKU-14",
    },
    {
      id: "id-15",
      name: "Product 15",
      price: 150,
      stock: 75,
      category: "Category 15",
      status: "PUBLISHED",
      sku: "SKU-15",
    },
    {
      id: "id-16",
      name: "Product 16",
      price: 160,
      stock: 80,
      category: "Category 16",
      status: "DRAFT",
      sku: "SKU-16",
    },
    {
      id: "id-17",
      name: "Product 17",
      price: 170,
      stock: 85,
      category: "Category 17",
      status: "PUBLISHED",
      sku: "SKU-17",
    },
    {
      id: "id-18",
      name: "Product 18",
      price: 180,
      stock: 90,
      category: "Category 18",
      status: "DRAFT",
      sku: "SKU-18",
    },
    {
      id: "id-19",
      name: "Product 19",
      price: 190,
      stock: 95,
      category: "Category 19",
      status: "PUBLISHED",
      sku: "SKU-19",
    },
    {
      id: "id-20",
      name: "Product 20",
      price: 200,
      stock: 100,
      category: "Category 20",
      status: "DRAFT",
      sku: "SKU-20",
    },
  ];
}

const page = async () => {
  const data = await getData();
  return <DisplayPanel title="Products" columns={columns} data={data} />;
};

export default page;
